convert to TS
worlve/sp-markdown-partitioner pull request #1
Opened 2020-03-16 17:59 UTC by Pergamene

2020-03-19 16:34 UTC, rhyeen requested changes

2020-03-19 16:34 UTC, rhyeen commented on src/markdown-to-inner-partitions.ts
> +export function generateInnerPartitions(markdownSubstring: string): object | null {
`object` should be `Partition[]` instead

2020-03-19 16:34 UTC, rhyeen commented on src/markdown-to-inner-partitions.ts
> +export function generateInnerPartitions(markdownSubstring: string): object | null {
Also, don't return `null`.  Either return an empty `Partition[]` or throw an error.

2020-03-19 16:34 UTC, rhyeen commented on src/markdown-to-inner-partitions.ts
> +  let partitions = [];
const

2020-03-19 16:34 UTC, rhyeen commented on src/markdown-to-inner-partitions.ts
> +  let currentChar: string, close: number;
on separate lines

2020-03-19 16:34 UTC, rhyeen commented on src/markdown-to-inner-partitions.ts
> +  let partitions = generateInnerPartitions(markdownSubstring);  //@TODO: NEED TYPE? (see line 57)
const

2020-03-19 16:34 UTC, rhyeen commented on src/markdown-to-inner-partitions.ts
> +function _buildBoldPartition(markdownSubstring: string): object {
Fix this an all following returns to be `Partition` or whatever other class is actually returned.

2020-03-19 16:34 UTC, rhyeen commented on src/markdown-to-inner-partitions.ts
> +    return { type: PARTITION_TYPES.BOLD, value: markdownSubstring.replace(/\\/g, '') };
Won't need `PARTITION_TYPES.*` once you have a `Partition` class and a `BoldPartition` class that extends it.

2020-03-20 02:44 UTC, Pergamene commented on src/markdown-to-inner-partitions.ts
> +export function generateInnerPartitions(markdownSubstring: string): object | null {
What is wrong with `null`?  I'll have to see if I'm checking for `null` in other places.

2020-03-22 23:34 UTC, Pergamene commented
Copied in your file, but I removed all `PageDetail` from the namings since my project doesn't have the context of page details.  Is that going to screw things up in spiderweb?

2022-02-12 16:39 UTC, closed without merging